/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Calculator {
  constructor()
  add(v: number): number
}

export declare function asyncTask(input: string): Promise<string>

export declare function divide(a: number, b: number): number

export declare function plus100(input: number): number
